### ISSUE TITLE
Mover Variables de [Object] a [App] para mejor compatibilidad entre escenas

### ISSUE THREAD

**Issue by cesar-moya** [zamatallica/InfinityKnot_SandBox_Collab#2]
Shh ahi le mando una task jaja, cuando tenga chance pa q mueva las variables que tiene en tipo Object a tipo App para no tener que estar dando copy paste.

![image](https://user-images.githubusercontent.com/1911332/95152072-15815c00-0741-11eb-92b6-63d6c0b5ade2.png)

**Comment by zamatallica** [comment]
Sin cambios, variables solo pertenecen al objeto.  Controller Interface causa probalemas haciendola de App, la regrese a que se quedara como variable de objecto, el Objeto ahora es un Prefab.
